# Generated by Django 2.1.7 on 2019-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField(verbose_name='Time')),
            ],
        ),
    ]
