# Generated by Django 2.1.7 on 2019-03-21 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('techer_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('designation', models.CharField(max_length=30)),
                ('joined', models.DateField(verbose_name='Year-Month')),
                ('phone', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_bio', models.TextField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('birthdate', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('englis_skill', models.CharField(max_length=10)),
                ('math_skill', models.CharField(blank=True, max_length=10, null=True)),
                ('programming_skill', models.CharField(blank=True, max_length=10, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
    ]
