# Generated by Django 2.1.7 on 2019-03-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
