# Generated by Django 2.1.7 on 2019-03-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_guardian_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='student_name',
        ),
    ]
